version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./public:/var/www/html
    networks:
      - laravel
    depends_on:
      - db

  web:
    volumes:
        - ./public:/var/www/html
    ports:
        - "8000:8000"
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - laravel
    volumes:
      - db_data:/var/lib/mysql

networks:
  laravel:

volumes:
  db_data:
